owner: ardqwxuser 
sites:
  - name: TacoSMP Site
    url: https://tacosmp.com
  - name: TacoProject Site
    url: https://tacoproject.com.tr
  - name: TacoSMP Minecraft
    url: https://api.mcsrvstat.us/2/mc.tacosmp.com
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: status.tacoproject.com.tr
  baseUrl: /
  logoUrl: https://tacoproject.com.tr/app/main/theme/assets/img/uploads/2c547b861cbb8410138f80ff0077cadd.png?v=1761821050
  name: TacoStatus
  introTitle: "**Servislerin Durum Sayfası** — Web siteleri ve Minecraft sunucularını anlık olarak izler."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ardqwxuser/TacoStatus
  skipdelays: true 

notifications:
  - type: discord
    webhook: 
    priority: null

